### PR TITLE
SignIn fetch userInfo.

### PR DESCRIPTION
**Pull request by leichunfeng**

### CODE REVIEW

**Comment by joshaber** [comment]
Thanks for the pull request! Could you give us a bit more context on this change?

**Comment by leichunfeng** [comment]
Of course. Just like the `+ (RACSignal *)signInToServerUsingWebBrowser:(OCTServer *)server scopes:(OCTClientAuthorizationScopes)scopes` method dose in `OCTClient`. Once the user login success using the browser, I have been able to obtain the userInfo. So I don't need to send a separate request to fetch the userInfo.

**Comment by joshaber** [comment]
@leichunfeng Ah, I see, thanks!

@octokit/octokit-objc Any thoughts here? This makes sense to me.

**Comment by jspahrsummers** [comment]
Replacing `rawLogin` with `login` isn't correct in the general case. The raw login should be the username you provide for authentication, while `login` is the “canonical” username for the GitHub APIs.

In the case of LDAP authentication, `rawLogin` may contain special LDAP characters that GitHub doesn't support, so it should only be used for the auth flow. `login` would be the normalized version of that, and could be passed to GitHub APIs that accept usernames.

**Comment by leichunfeng** [comment]
I have fixed the problem about the assignment of rawLogin.

But the already exists method `+ (RACSignal *)signInToServerUsingWebBrowser:(OCTServer *)server scopes:(OCTClientAuthorizationScopes)scopes` in `OCTClient` had the same problem and may be can not using the same way to fix it.

**Comment by joshaber** [comment]
_assigning to @jspahrsummers since he has a better understanding of `rawLogin` problems._

**Comment by jspahrsummers** [comment]
> But the already exists method `+ (RACSignal *)signInToServerUsingWebBrowser:(OCTServer *)server scopes:(OCTClientAuthorizationScopes)scopes` in `OCTClient` had the same problem and may be can not using the same way to fix it.

That method doesn't accept a raw login, since the user signs in through the website. In fact, there's no possible `rawLogin` for that flow—we can only keep the username given to us by the GitHub API.

> I have fixed the problem about the assignment of rawLogin.

Hmm, I'm still a bit confused about this code. What problem is fixed by this newest revision?

**Comment by leichunfeng** [comment]
> Replacing rawLogin with login isn't correct in the general case. The raw login should be the username you provide for authentication, while login is the “canonical” username for the GitHub APIs.

So I replace the previous has problem code `if (user.rawLogin == nil) userDict[@keypath(user.rawLogin)] = user.login;` with `userDict[@keypath(user.rawLogin)] = client.user.rawLogin;`. Because I can retrieve the username which the user input just is the `rawLogin` when the user using the native login flow to log in.

**Comment by jspahrsummers** [comment]
Sorry for not being clear.

My question is: what _error_ or _bug_ does this fix? Is there a behavior that occurs before this pull request that is now different after this change?

**Comment by leichunfeng** [comment]
Nothing. I just add a chaining operation `fetchUserInfo`.

> Of course. Just like the + (RACSignal *)signInToServerUsingWebBrowser:(OCTServer *)server scopes:(OCTClientAuthorizationScopes)scopes method dose in OCTClient. Once the user login success using the browser, I have been able to obtain the userInfo. So I don't need to send a separate request to fetch the userInfo.

**Comment by jspahrsummers** [comment]
Ah, I see.

Since not everyone may want to make that request (for example, because they don't need the data), it doesn't seem like the library should automatically do it. :confused: 

Thanks for the pull request, though! :sparkles:

**Pull request closed without merging**
