### PR TITLE
Add `subscribersCount` property to `OCTRepository`.

### PR DESCRIPTION
**Pull request by leichunfeng**

### CODE REVIEW

**Comment by joshaber** [comment]
Thanks! Could you update `OCTRepositorySpec.m` to include this new property?

**Comment by leichunfeng** [comment]
Yes, I have already finished it. But I have a question that why not use the built-in unit-testing framework - e.g. `XCTest`. What are the benefits of using `Quick` and `Nimble` framework to do so?

**Comment by joshaber** [comment]
:metal:

**Comment by joshaber** [comment]
>Yes, I have already finished it. But I have a question that why not use the built-in unit-testing framework - e.g. XCTest. What are the benefits of using Quick and Nimble framework to do so?

We prefer them because the tests end up more succinct and require less boilerplate.

**Comment by leichunfeng** [comment]
Thank you for your reply.

**Pull request merged**
